"""
score_iaa_expansion.py
-----------------------
Scores the returned IAA expansion sheet and computes combined n=120 statistics.

Usage:
  python scripts/score_iaa_expansion.py \\
      --returned_sheet annotation/inter_annotator/iaa_expansion_ANNOTATOR_SHEET.csv \\
      [--patch_docx]   # also creates IndiaFinBench_v5_IAA.docx

Inputs:
  annotation/inter_annotator/iaa_expansion_REFERENCE.csv   (generated by Step 1)
  annotation/inter_annotator/kappa_report.csv              (original 60-item IAA)
  <returned_sheet>                                          (filled by annotator)

Outputs:
  Console: combined n=120 table ready to paste into the paper
  [--patch_docx]: IndiaFinBench_v5_IAA.docx
"""

import argparse
import csv
import io
import os
import re
import sys
import zipfile
import shutil

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")

try:
    from rapidfuzz import fuzz as _rapidfuzz_fuzz  # noqa: F401
except ImportError:
    raise ImportError("rapidfuzz required: pip install rapidfuzz")

try:
    from sklearn.metrics import cohen_kappa_score
except ImportError:
    raise ImportError("scikit-learn required: pip install scikit-learn")

REFERENCE_PATH  = "annotation/inter_annotator/iaa_expansion_REFERENCE.csv"
ORIGINAL_IAA    = "annotation/inter_annotator/kappa_report.csv"
SRC_DOCX        = "IndiaFinBench_v4_Final.docx"
DST_DOCX        = "IndiaFinBench_v5_IAA.docx"

TASK_ORDER = [
    "regulatory_interpretation",
    "numerical_reasoning",
    "contradiction_detection",
    "temporal_reasoning",
]
SHORT = {
    "regulatory_interpretation": "REG",
    "numerical_reasoning":       "NUM",
    "contradiction_detection":   "CON",
    "temporal_reasoning":        "TMP",
}


# ── Scoring ───────────────────────────────────────────────────────────────────

def normalise(text: str) -> str:
    if not text:
        return ""
    t = str(text).lower().strip()
    t = re.sub(r"[^\w\s%.]", " ", t)
    return re.sub(r"\s+", " ", t).strip()


def extract_yn(text: str) -> str:
    t = normalise(text)
    if t.startswith("yes"):
        return "yes"
    if t.startswith("no"):
        return "no"
    return "unclear"


def score_pair(ref: str, pred: str, task_type: str) -> int:
    """4-stage matching: exact → fuzzy token → numerical → Yes/No (CON)."""
    from rapidfuzz import fuzz

    if not pred:
        return 0

    if task_type == "contradiction_detection":
        return int(extract_yn(ref) == extract_yn(pred))

    rn, pn = normalise(ref), normalise(pred)

    # Stage 1: exact match (case-normalised, punctuation stripped)
    if rn == pn:
        return 1

    # Stage 2: numerical extraction match
    nums_r = set(re.findall(r"\d[\d,]*\.?\d*", rn))
    nums_p = set(re.findall(r"\d[\d,]*\.?\d*", pn))
    if nums_r and nums_p and nums_r == nums_p:
        return 1

    # Stage 3: fuzzy token match
    if fuzz.token_set_ratio(rn, pn) / 100.0 >= 0.72:
        return 1

    return 0


# ── Load original 60-item results from kappa_report.csv ──────────────────────

def load_original_60(path: str) -> dict:
    """Returns {task_type: [agree_int, ...]} from the original 60-item IAA."""
    results: dict[str, list] = {t: [] for t in TASK_ORDER}
    if not os.path.exists(path):
        print(f"  WARN: {path} not found — original 60 items not included.")
        return results
    with open(path, encoding="utf-8") as f:
        for row in csv.DictReader(f):
            t = row.get("task_type", "")
            if t in results:
                results[t].append(int(row["agree"]))
    return results


# ── Score the returned expansion sheet ───────────────────────────────────────

def score_expansion(returned_path: str) -> dict:
    """Returns {task_type: [(agree_int, ref_yn, ann_yn), ...]} for n=60 new items."""
    # Load reference answers
    ref_map: dict[str, dict] = {}
    with open(REFERENCE_PATH, encoding="utf-8") as f:
        for row in csv.DictReader(f):
            ref_map[row["item_id"]] = row

    results: dict[str, list] = {t: [] for t in TASK_ORDER}
    con_ref_labels: list[str] = []
    con_ann_labels: list[str] = []

    with open(returned_path, encoding="utf-8") as f:
        for row in csv.DictReader(f):
            item_id = row.get("item_id", "").strip()
            ann_ans = row.get("YOUR_ANSWER", "").strip()

            if item_id not in ref_map:
                print(f"  WARN: item_id {item_id!r} not in reference — skipping")
                continue

            ref_row  = ref_map[item_id]
            task     = ref_row["task_type"]
            ref_ans  = ref_row["reference_answer"]

            agree = score_pair(ref_ans, ann_ans, task)
            results[task].append(agree)

            if task == "contradiction_detection":
                con_ref_labels.append(extract_yn(ref_ans))
                con_ann_labels.append(extract_yn(ann_ans))

    return results, con_ref_labels, con_ann_labels


# ── Print combined table ──────────────────────────────────────────────────────

def print_combined_table(orig: dict, exp_results: dict,
                         exp_con_ref: list, exp_con_ann: list):
    print()
    print(f"  {'━'*68}")
    print(f"  IndiaFinBench — Combined IAA Report (n=120)")
    print(f"  {'━'*68}")
    print(f"  {'Task Type':<32}  {'n_orig':>6}  {'n_new':>5}  {'n_total':>7}  {'Agree%':>7}  {'κ':>7}")
    print(f"  {'─'*32}  {'─'*6}  {'─'*5}  {'─'*7}  {'─'*7}  {'─'*7}")

    combined: dict[str, dict] = {}
    all_agrees: list[int] = []

    con_ref_all: list[str] = []
    con_ann_all: list[str] = []

    # Rebuild CON labels from original kappa_report for kappa calculation
    orig_con_ref: list[str] = []
    orig_con_ann: list[str] = []
    if os.path.exists(ORIGINAL_IAA):
        with open(ORIGINAL_IAA, encoding="utf-8") as f:
            for row in csv.DictReader(f):
                if row.get("task_type") == "contradiction_detection":
                    orig_con_ref.append(extract_yn(row.get("ref_answer", "")))
                    orig_con_ann.append(extract_yn(row.get("ann2_answer", "")))

    for t in TASK_ORDER:
        o = orig.get(t, [])
        e = exp_results.get(t, [])
        combined_agrees = o + e
        n_orig  = len(o)
        n_new   = len(e)
        n_total = len(combined_agrees)
        agree_pct = sum(combined_agrees) / n_total * 100 if n_total else 0.0
        all_agrees.extend(combined_agrees)

        kappa_str = "    N/A"
        kappa_val = None
        if t == "contradiction_detection":
            all_con_ref = orig_con_ref + exp_con_ref
            all_con_ann = orig_con_ann + exp_con_ann
            con_ref_all = all_con_ref
            con_ann_all = all_con_ann
            if len(set(all_con_ref)) > 1 and len(set(all_con_ann)) > 1:
                try:
                    kappa_val = cohen_kappa_score(all_con_ref, all_con_ann)
                    kappa_str = f"  {kappa_val:>5.3f}"
                except Exception:
                    kappa_str = "   ERR"

        combined[t] = {
            "n_orig":    n_orig,
            "n_new":     n_new,
            "n_total":   n_total,
            "agree_pct": agree_pct,
            "kappa":     kappa_val,
            "kappa_str": kappa_str,
        }
        print(f"  {t:<32}  {n_orig:>6}  {n_new:>5}  {n_total:>7}  {agree_pct:>6.1f}%  {kappa_str}")

    overall_agree = sum(all_agrees) / len(all_agrees) * 100 if all_agrees else 0.0
    n_total = len(all_agrees)
    print(f"  {'─'*32}  {'─'*6}  {'─'*5}  {'─'*7}  {'─'*7}  {'─'*7}")
    print(f"  {'OVERALL':<32}  {'':>6}  {'':>5}  {n_total:>7}  {overall_agree:>6.1f}%       --")
    print(f"  {'━'*68}")
    print()

    # Compute CON kappa
    con_kappa = combined["contradiction_detection"]["kappa"]

    print("  ── Paste into paper (Table 4 values) ──")
    print(f"  REG: n={combined['regulatory_interpretation']['n_total']}, agree={combined['regulatory_interpretation']['agree_pct']:.1f}%, κ=—")
    print(f"  NUM: n={combined['numerical_reasoning']['n_total']}, agree={combined['numerical_reasoning']['agree_pct']:.1f}%, κ=—")
    print(f"  CON: n={combined['contradiction_detection']['n_total']}, agree={combined['contradiction_detection']['agree_pct']:.1f}%, κ={con_kappa:.3f}" if con_kappa else f"  CON: n={combined['contradiction_detection']['n_total']}, agree={combined['contradiction_detection']['agree_pct']:.1f}%")
    print(f"  TMP: n={combined['temporal_reasoning']['n_total']}, agree={combined['temporal_reasoning']['agree_pct']:.1f}%, κ=—")
    print(f"  Overall: n={n_total}, agree={overall_agree:.1f}%")
    print()

    return combined, overall_agree, n_total


# ── Docx patching ─────────────────────────────────────────────────────────────

def patch_docx(combined: dict, overall_agree: float, n_total: int, con_kappa: float):
    print(f"  Patching {SRC_DOCX} → {DST_DOCX} ...")

    # Unpack source docx to a temp directory
    tmp_dir = "_iaa_docx_tmp"
    if os.path.exists(tmp_dir):
        shutil.rmtree(tmp_dir)
    with zipfile.ZipFile(SRC_DOCX) as z:
        z.extractall(tmp_dir)

    xml_path = os.path.join(tmp_dir, "word", "document.xml")
    with open(xml_path, encoding="utf-8") as f:
        content = f.read()

    def rep(old, new, label):
        nonlocal content
        if old not in content:
            print(f"    WARN not found: {label}")
            return False
        content = content.replace(old, new, 1)
        print(f"    OK: {label}")
        return True

    reg = combined["regulatory_interpretation"]
    num = combined["numerical_reasoning"]
    con = combined["contradiction_detection"]
    tmp_t = combined["temporal_reasoning"]

    reg_n   = reg["n_total"];  reg_pct  = f"{reg['agree_pct']:.1f}%"
    num_n   = num["n_total"];  num_pct  = f"{num['agree_pct']:.1f}%"
    con_n   = con["n_total"];  con_pct  = f"{con['agree_pct']:.1f}%"
    tmp_n   = tmp_t["n_total"]; tmp_pct = f"{tmp_t['agree_pct']:.1f}%"
    ov_pct  = f"{overall_agree:.1f}%"
    kap_str = f"{con_kappa:.3f}" if con_kappa is not None else "0.611"

    # 1. Abstract
    rep(
        "a separate 60-item human inter-annotator agreement evaluation "
        f"(κ = 0.611 for contradiction detection; 76.7% overall agreement)",
        f"a separate 120-item human inter-annotator agreement evaluation "
        f"(κ = {kap_str} for contradiction detection; {ov_pct} overall agreement)",
        "Abstract: 60-item → 120-item, update kappa + overall",
    )

    # 2. Introduction contributions bullet
    rep(
        "inter-annotator agreement evaluation on 60 items",
        "inter-annotator agreement evaluation on 120 items",
        "Intro contributions: 60 → 120",
    )

    # 3. Section 3.5 opening
    rep(
        "60 randomly selected items",
        "120 randomly selected items",
        "Section 3.5 opening: 60 → 120",
    )

    # 4. Human pass depth line
    rep(
        "human pass provides depth (60 items with independent human judgment)",
        "human pass provides depth (120 items with independent human judgment)",
        "Human pass depth: 60 → 120",
    )

    # 5. Table 4 caption
    rep(
        "Table 4. Human inter-annotator agreement (60-item sample).",
        "Table 4. Human inter-annotator agreement (120-item sample).",
        "Table 4 caption: 60-item → 120-item",
    )

    # 6. Table 4 values — update per-task n and agreement %
    # REG row: n=11 → n=reg_n, 100.0% → reg_pct
    rep(f"<w:t>Regulatory Interpretation", f"<w:t>Regulatory Interpretation",
        "REG row anchor (no-op check)")
    rep(
        f"<w:t>Regulatory Interpretation</w:t></w:r></w:p></w:tc><w:tc>"
        f"<w:tcPr><w:tcW w:type=\"dxa\" w:w=\"1008\"/><w:tcBorders>"
        f"<w:top w:val=\"single\" w:sz=\"4\" w:color=\"000000\"/>"
        f"<w:left w:val=\"single\" w:sz=\"4\" w:color=\"000000\"/>"
        f"<w:bottom w:val=\"single\" w:sz=\"4\" w:color=\"000000\"/>"
        f"<w:right w:val=\"single\" w:sz=\"4\" w:color=\"000000\"/>"
        f"<w:insideH w:val=\"none\"/><w:insideV w:val=\"none\"/>"
        f"</w:tcBorders></w:tcPr><w:p><w:r><w:rPr>"
        f"<w:rFonts w:ascii=\"Times New Roman\" w:hAnsi=\"Times New Roman\"/>"
        f"<w:sz w:val=\"22\"/></w:rPr><w:t>11</w:t>",
        f"<w:t>Regulatory Interpretation</w:t></w:r></w:p></w:tc><w:tc>"
        f"<w:tcPr><w:tcW w:type=\"dxa\" w:w=\"1008\"/><w:tcBorders>"
        f"<w:top w:val=\"single\" w:sz=\"4\" w:color=\"000000\"/>"
        f"<w:left w:val=\"single\" w:sz=\"4\" w:color=\"000000\"/>"
        f"<w:bottom w:val=\"single\" w:sz=\"4\" w:color=\"000000\"/>"
        f"<w:right w:val=\"single\" w:sz=\"4\" w:color=\"000000\"/>"
        f"<w:insideH w:val=\"none\"/><w:insideV w:val=\"none\"/>"
        f"</w:tcBorders></w:tcPr><w:p><w:r><w:rPr>"
        f"<w:rFonts w:ascii=\"Times New Roman\" w:hAnsi=\"Times New Roman\"/>"
        f"<w:sz w:val=\"22\"/></w:rPr><w:t>{reg_n}</w:t>",
        f"Table 4 REG n: 11 → {reg_n}",
    )

    # Update REG agreement %
    # The 100.0% in Table 4 is unique enough to find, but check there's not another
    # We target the one inside the table (after the REG items cell)
    # Use a more targeted anchor: the sequence <w:t>100.0%</w:t> inside the table
    # The table cell structure: ...100.0%...</w:t>...</w:t>—...</w:t>
    rep(
        f"<w:t>100.0%</w:t></w:r></w:p></w:tc><w:tc>"
        f"<w:tcPr><w:tcW w:type=\"dxa\" w:w=\"1584\"/>",
        f"<w:t>{reg_pct}</w:t></w:r></w:p></w:tc><w:tc>"
        f"<w:tcPr><w:tcW w:type=\"dxa\" w:w=\"1584\"/>",
        f"Table 4 REG agree%: 100.0% → {reg_pct}",
    )

    # TMP row: n=16 → tmp_n, 87.5% → tmp_pct
    rep(
        f"<w:t>87.5%</w:t></w:r></w:p></w:tc><w:tc>"
        f"<w:tcPr><w:tcW w:type=\"dxa\" w:w=\"1584\"/>",
        f"<w:t>{tmp_pct}</w:t></w:r></w:p></w:tc><w:tc>"
        f"<w:tcPr><w:tcW w:type=\"dxa\" w:w=\"1584\"/>",
        f"Table 4 TMP agree%: 87.5% → {tmp_pct}",
    )

    # CON row: n=17 → con_n, 82.4% → con_pct, kappa 0.611 → kap_str
    rep(
        f"<w:t>82.4%</w:t></w:r></w:p></w:tc><w:tc>"
        f"<w:tcPr><w:tcW w:type=\"dxa\" w:w=\"1584\"/>",
        f"<w:t>{con_pct}</w:t></w:r></w:p></w:tc><w:tc>"
        f"<w:tcPr><w:tcW w:type=\"dxa\" w:w=\"1584\"/>",
        f"Table 4 CON agree%: 82.4% → {con_pct}",
    )
    rep("<w:t>0.611</w:t>", f"<w:t>{kap_str}</w:t>",
        f"Table 4 CON kappa: 0.611 → {kap_str}")

    # NUM row: n=16 → num_n, 43.8% → num_pct
    rep(
        f"<w:t>43.8%</w:t></w:r></w:p></w:tc><w:tc>"
        f"<w:tcPr><w:tcW w:type=\"dxa\" w:w=\"1584\"/>",
        f"<w:t>{num_pct}</w:t></w:r></w:p></w:tc><w:tc>"
        f"<w:tcPr><w:tcW w:type=\"dxa\" w:w=\"1584\"/>",
        f"Table 4 NUM agree%: 43.8% → {num_pct}",
    )

    # Overall row: n=60 → 120, 76.7% → ov_pct
    rep(
        f"<w:t>60</w:t></w:r></w:p></w:tc><w:tc>"
        f"<w:tcPr><w:tcW w:type=\"dxa\" w:w=\"1440\"/>",
        f"<w:t>{n_total}</w:t></w:r></w:p></w:tc><w:tc>"
        f"<w:tcPr><w:tcW w:type=\"dxa\" w:w=\"1440\"/>",
        f"Table 4 Overall n: 60 → {n_total}",
    )
    rep(
        f"<w:t>76.7%</w:t></w:r></w:p></w:tc><w:tc>"
        f"<w:tcPr><w:tcW w:type=\"dxa\" w:w=\"1584\"/>",
        f"<w:t>{ov_pct}</w:t></w:r></w:p></w:tc><w:tc>"
        f"<w:tcPr><w:tcW w:type=\"dxa\" w:w=\"1584\"/>",
        f"Table 4 Overall agree%: 76.7% → {ov_pct}",
    )

    # Update individual n values in Table 4 rows
    # TMP n=16 (appears in TMP row between Temporal Reasoning and 87.5%)
    # Use the unique sequence: Temporal Reasoning row -> 16 -> 87.5%
    # We need to replace the specific "16" in TMP row before "87.5%" becomes tmp_pct
    # Since we already replaced 87.5% → tmp_pct, we can match by adjacent context
    # The structure is: ...Temporal Reasoning</w:t>...16</w:t>...<tmp_pct>
    # We'll do a regex-based replacement for TMP n
    pattern_tmp_n = (
        r'(<w:t>Temporal Reasoning</w:t>.*?'
        r'<w:tcW w:type="dxa" w:w="1008"/>.*?<w:t>)'
        r'16'
        r'(</w:t>)'
    )
    new_content = re.sub(pattern_tmp_n,
                         lambda m: m.group(1) + str(tmp_n) + m.group(2),
                         content, count=1, flags=re.DOTALL)
    if new_content != content:
        content = new_content
        print(f"    OK: Table 4 TMP n: 16 → {tmp_n}")
    else:
        print(f"    WARN not found: Table 4 TMP n pattern")

    # CON n=17
    pattern_con_n = (
        r'(<w:t>Contradiction Detection</w:t>.*?'
        r'<w:tcW w:type="dxa" w:w="1008"/>.*?<w:t>)'
        r'17'
        r'(</w:t>)'
    )
    new_content = re.sub(pattern_con_n,
                         lambda m: m.group(1) + str(con_n) + m.group(2),
                         content, count=1, flags=re.DOTALL)
    if new_content != content:
        content = new_content
        print(f"    OK: Table 4 CON n: 17 → {con_n}")
    else:
        print(f"    WARN not found: Table 4 CON n pattern")

    # NUM n=16 (second occurrence; TMP is first)
    pattern_num_n = (
        r'(<w:t>Numerical Reasoning</w:t>.*?'
        r'<w:tcW w:type="dxa" w:w="1008"/>.*?<w:t>)'
        r'16'
        r'(</w:t>)'
    )
    new_content = re.sub(pattern_num_n,
                         lambda m: m.group(1) + str(num_n) + m.group(2),
                         content, count=1, flags=re.DOTALL)
    if new_content != content:
        content = new_content
        print(f"    OK: Table 4 NUM n: 16 → {num_n}")
    else:
        print(f"    WARN not found: Table 4 NUM n pattern")

    # REG n=11
    pattern_reg_n = (
        r'(<w:t>Regulatory Interpretation</w:t>.*?'
        r'<w:tcW w:type="dxa" w:w="1008"/>.*?<w:t>)'
        r'11'
        r'(</w:t>)'
    )
    new_content = re.sub(pattern_reg_n,
                         lambda m: m.group(1) + str(reg_n) + m.group(2),
                         content, count=1, flags=re.DOTALL)
    if new_content != content:
        content = new_content
        print(f"    OK: Table 4 REG n: 11 → {reg_n}")
    else:
        print(f"    WARN not found: Table 4 REG n pattern")

    # 7. Section 7.3 Limitation 4: update 60 → 120, remove expansion recommendation
    old_lim = (
        "the human IAA evaluation covers 60 of the 406 items; "
        "extending human agreement measurement to the full benchmark would "
        "provide stronger statistical guarantees, though the current sample is "
        "representative across all four task types and difficulty levels."
    )
    new_lim = (
        f"the human IAA evaluation covers 120 of the 406 items (29.6%), "
        "which exceeds the 20% coverage threshold and is representative "
        "across all four task types and difficulty levels."
    )
    rep(old_lim, new_lim, "Limitation 4: 60 → 120 + remove expansion recommendation")

    # 8. Update kappa and agreement values in Section 3.5 narrative text
    # The abstract already updated κ = 0.611 → new kappa and 76.7% → new overall
    # Also update any inline mention of 76.7% in section 3.5
    rep(
        "κ = 0.611 for contradiction detection falls in the 'substantial agreement' band",
        f"κ = {kap_str} for contradiction detection falls in the 'substantial agreement' band",
        "Section 3.5 narrative: kappa value",
    )
    rep(
        "The lower numerical reasoning agreement (43.8%)",
        f"The lower numerical reasoning agreement ({num_pct})",
        "Section 3.5 narrative: NUM agreement %",
    )

    # Write patched XML
    with open(xml_path, "w", encoding="utf-8") as f:
        f.write(content)

    # Repack to new docx
    with zipfile.ZipFile(DST_DOCX, "w", zipfile.ZIP_DEFLATED) as zout:
        for dirpath, _dirnames, filenames in os.walk(tmp_dir):
            for fname in filenames:
                full = os.path.join(dirpath, fname)
                arcname = os.path.relpath(full, tmp_dir).replace("\\", "/")
                zout.write(full, arcname)

    shutil.rmtree(tmp_dir)
    print(f"    Saved: {DST_DOCX}")


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--returned_sheet", required=True,
                        help="Path to the filled annotator CSV")
    parser.add_argument("--patch_docx", action="store_true",
                        help="Also create IndiaFinBench_v5_IAA.docx")
    args = parser.parse_args()

    if not os.path.exists(args.returned_sheet):
        print(f"ERROR: returned sheet not found: {args.returned_sheet}")
        sys.exit(1)
    if not os.path.exists(REFERENCE_PATH):
        print(f"ERROR: reference file not found: {REFERENCE_PATH}")
        print("  Run generate_iaa_expansion.py first.")
        sys.exit(1)

    print(f"\n  Scoring expansion sheet: {args.returned_sheet}")

    # Score new 60 items
    exp_results, exp_con_ref, exp_con_ann = score_expansion(args.returned_sheet)

    # Load original 60-item data
    orig = load_original_60(ORIGINAL_IAA)

    # Print combined table and collect stats
    combined, overall_agree, n_total = print_combined_table(
        orig, exp_results, exp_con_ref, exp_con_ann
    )

    con_kappa = combined["contradiction_detection"]["kappa"]

    if args.patch_docx:
        if not os.path.exists(SRC_DOCX):
            print(f"  ERROR: source docx not found: {SRC_DOCX}")
        else:
            patch_docx(combined, overall_agree, n_total, con_kappa)


if __name__ == "__main__":
    main()
